/*
 * Copyright:
 *   2011 Derrell Lipman
 *
 * License:
 *   LGPL: http://www.gnu.org/licenses/lgpl.html
 *   EPL: http://www.eclipse.org/org/documents/epl-v10.php
 *   See the LICENSE file in the project's top-level directory for details.
 *
 * Authors:
 *   * Derrell Lipman (derrell)
 */

/*
#asset(rpcjs/*)
*/

/**
 * Origin constants
 */
qx.Class.define("rpcjs.rpc.error.Origin",
{
  extend : qx.core.Object,

  /**
   * Error Origin values
   */
  statics :
  {
    /**
     * The error was detected by the generic JSON-RPC Server.
     */
    Server      : 1,
    
    /**
     * The error was detected by, or generated by a remote procedure call
     * method.
     */
    Application : 2,
    
    /**
     * An error occurred in the transport between client and server. This error
     * is never generated by the server.
     */
    Transport   : 3,
    
    /**
     * The client detected or generated the error. This error is never generated
     * by the server.
     */
    Client      : 4
  }
});
